<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="/assets/js/prism.js"></script>
<link rel="stylesheet" href="/assets/css/prism.css">
<a href="/index.php">Home</a>
<?php
/*
*************problem 2****************

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

function fibonacci_evenSum($end){ //set $end point for function
	//set variables
	$fib1 = 1;
	$fib2 = 2;
	$fib3 = '';
	$sequence = array();
	//echo first even number
	array_push($sequence, $fib2);

	while ($fib1 + $fib2 < $end) {
		$fib3 = $fib1 + $fib2;
		if($fib3 % 2 === 0){
			array_push($sequence, $fib3);
		}
		$fib1 = $fib2;
		$fib2 = $fib3;
	}
	echo array_sum($sequence);
}

?>

<!-- *********DISPLAY********** -->
<h2>problem 2</h2>
<h4>Even Fibonacci Numbers</h4>
<hr>

<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:</p>

<p>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>

<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
<hr><!-- *****CODE***** -->

<code class="language-php"><pre class="line-numbers">
function fibonacci_evenSum($end){ //set $end point for function
	//set variables
	$fib1 = 1;
	$fib2 = 2;
	$fib3 = '';
	$sequence = array();
	//echo first even number
	array_push($sequence, $fib2);

	while ($fib1 + $fib2 < $end) {
		$fib3 = $fib1 + $fib2;
		if($fib3 % 2 === 0){
			array_push($sequence, $fib3);
		}
		$fib1 = $fib2;
		$fib2 = $fib3;
	}
	echo array_sum($sequence);
}

fibonacci_evenSum(4000000);
</pre></code>
<hr><!-- *****OUTPUT***** -->
<?php 

fibonacci_evenSum(4000000);

 ?>